### ISSUE TITLE
I get the following error when a new media is added

### ISSUE THREAD

**Issue by magoespa** [Fahmula/emby-telegram-notifier#15]
I can send successfully test notification by following the configuration steps but when a new media is added I get the following error:

2024-03-03 10:25:47,364 - ERROR - Failed to retrieve item details: 401 Client Error: Unauthorized for url: http://192.168.0.102:8096//emby/Items?api_key=XXXXXX&Recursive=true&Fields=Overview%2CPremiereDate%2CProviderIds%2CRemoteTrailers%2CProductionYear%2CDateCreated&Ids=253552
Exception in thread Thread-1 (process_payload):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/app.py", line 147, in process_payload
    if not item_details["Items"][0].get("Overview"):
           ~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by Fahmula** [comment]
Are you sure you're using the correct API key?
