### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by Antonio01p** [Fahmula/emby-telegram-notifier#20]
Hi, I wanted to know if you could help me configure the app.py file by setting the exact parameters

# Telegram Configuration
TELEGRAM_BOT_TOKEN = os.environ.get("")
TELEGRAM_CHAT_ID = os.environ.get("")
EMBY_BASE_URL = os.environ.get("")
EMBY_API_KEY = os.environ.get("")

in the emby base url section do I put http://localhost:8096/ or the local or remote address of the server?

Because I tried with both and I get this when I start the app.py file

* Serving Flask app 'app'
 * Debug mode: off
2024-10-30 18:36:44,546 - INFO - ←[31m←[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.←[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.1.14:5000
2024-10-30 18:36:44,548 - INFO - ←[33mPress CTRL+C to quit←[0m

and if I configure the notifications also by putting both urls and inserting, multipart/form-data or application/json I do not receive any test notification. If you can understand something, I've been a couple of days but nothing.

**Comment by Antonio01p** [comment]
when i add new content i get this response from the program.



2024-10-31 11:26:55,908 - ERROR - Failed to retrieve item details: Invalid URL 'None/emby/Items': No scheme supplied. Perhaps you meant https://None/emby/Items?
Exception in thread Thread-280 (process_payload):
Traceback (most recent call last):
  File "C:\Users\Antonio\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Users\Antonio\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 992, in run
    self._target(*self._args, **self._kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Antonio\Desktop\Nuova cartella (2)\emby-telegram-notifier-main\app.py", line 145, in process_payload
    if not item_details["Items"][0].get("Overview"):
           ~~~~~~~~~~~~^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by 2-click** [comment]
Python doesn't find the URL of emby, it's "null" / "none". You should have it specified but I cannot tell you the mistake you've done for sure as your issue misses lots of information.

**Comment by Antonio01p** [comment]
in the EMBY BASEURL = os.environ.get("") configuration I insert http://localhost:8096, I also tried the server address but no same error.

**Comment by Fahmula** [comment]
@Antonio01p Can you show me a picture of your docker compose?
